### ISSUE TITLE
Error installing pyunicorn 

### ISSUE THREAD

**Issue by arjunChaudharyUnimelb** [pik-copan/pyunicorn#170] opened 2022-09-02 06:47 UTC
Hi Guys,

I am trying to install pyunicorn package on Windows 10 to generate Recurrence Plot. However, I am facing issues. I have followed some of the online thread to install Cython package which has solved some issues but I am still unable to install the package.

After running "`pip3 install pyunicorn`". There is a bunch of errors however, when I searched for term "error". I can see following error:

```
pip-install-4smwgquo\pyunicorn_b945c392248f4c0990844cdab31f5d77\pyunicorn\climate\_ext\src_numerics.c(196): error C2057: expected constant expression
pip-install-4smwgquo\pyunicorn_b945c392248f4c0990844cdab31f5d77\pyunicorn\climate\_ext\src_numerics.c(196): error C2466: cannot allocate an array of constant size 0
pip-install-4smwgquo\pyunicorn_b945c392248f4c0990844cdab31f5d77\pyunicorn\climate\_ext\src_numerics.c(196): error C2133: 'rankedi': unknown size
pip-install-4smwgquo\pyunicorn_b945c392248f4c0990844cdab31f5d77\pyunicorn\climate\_ext\src_numerics.c(197): error C2057: expected constant expression
pip-install-4smwgquo\pyunicorn_b945c392248f4c0990844cdab31f5d77\pyunicorn\climate\_ext\src_numerics.c(197): error C2466: cannot allocate an array of constant size 0
pip-install-4smwgquo\pyunicorn_b945c392248f4c0990844cdab31f5d77\pyunicorn\climate\_ext\src_numerics.c(197): error C2133: 'rankedj': unknown size
pip-install-4smwgquo\pyunicorn_b945c392248f4c0990844cdab31f5d77\pyunicorn\climate\_ext\src_numerics.c(198): error C2057: expected constant expression
pip-install-4smwgquo\pyunicorn_b945c392248f4c0990844cdab31f5d77\pyunicorn\climate\_ext\src_numerics.c(198): error C2466: cannot allocate an array of constant size 0
pip-install-4smwgquo\pyunicorn_b945c392248f4c0990844cdab31f5d77\pyunicorn\climate\_ext\src_numerics.c(198): error C2133: 'normalizedi': unknown size
pip-install-4smwgquo\pyunicorn_b945c392248f4c0990844cdab31f5d77\pyunicorn\climate\_ext\src_numerics.c(199): error C2057: expected constant expression
pip-install-4smwgquo\pyunicorn_b945c392248f4c0990844cdab31f5d77\pyunicorn\climate\_ext\src_numerics.c(199): error C2466: cannot allocate an array of constant size 0
pip-install-4smwgquo\pyunicorn_b945c392248f4c0990844cdab31f5d77\pyunicorn\climate\_ext\src_numerics.c(199): error C2133: 'normalizedj': unknown size

```

Once this doesn't work. I tried to install it from github

```
conda create -n pyunicorn python=3.7
conda activate pyunicorn
pip install numpy scipy igraph
pip install git+https://github.com/pik-copan/pyunicorn
```
But this also fails.  Stating following:

```
Failed to build pyunicorn
ERROR: Could not build wheels for pyunicorn, which is required to install pyproject.toml-based projects
```
Going through logs I can see follwoing specific error:
```
Creating library build\temp.win-amd64-cpython-37\Release\src/pyunicorn/core/_ext\numerics.cp37-win_amd64.lib and object build\temp.win-amd64-cpython-37\Release\src/pyunicorn/core/_ext\numerics.cp37-win_amd64.exp
      numerics.obj : error LNK2001: unresolved external symbol drand48
      numerics.obj : error LNK2001: unresolved external symbol srand48
```

**Comment by zivgogogo** [comment] 2022-09-27 12:05
maybe you should try pip3 install Cython

**Comment by ntfrgl** [comment] 2023-06-27 07:58
I am closing this issue, since it is a duplicate of #160 with the same error messages and the same causes.

@arjunChaudharyUnimelb, could you please retry with the most recent `master` branch, and report back in the referenced issue? Thank you!

**Closed by ntfrgl** 2023-06-27 07:58 UTC
Labels: installation
