### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by drkousek** [pik-copan/pyunicorn#171] opened 2023-01-15 14:39 UTC
Hey!
I was not quite sucesfull in installing pyunicorn. After installation of build tools, i tried install it, but unsucesffully. It says some weird things and I am not able to install it.
Python version 3. 9. 9
No idea, why is that. Could you help me?
![image](https://user-images.githubusercontent.com/26819551/212547242-27c9d73b-3ab1-48ae-aac1-af3f6916e0e0.png)

**Comment by zugnachpankow** [comment] 2023-01-17 12:48
Hey, 

unfortunately we still face problems with windows installations. 

Do you have cython installed?

**Comment by drkousek** [comment] 2023-01-17 20:20
Yes, I have.

**Comment by ntfrgl** [comment] 2023-06-27 08:04
I am closing this issue, since it is a duplicate of #160 with the same error messages and the same causes.

@drkousek, could you please retry with the most recent `master` branch, and report back in the referenced issue? Thank you!

**Closed by ntfrgl** 2023-06-27 08:04 UTC
Labels: installation
