### ISSUE TITLE
Error installing pyunicorn 0.7.0 on Wndows 11

### ISSUE THREAD

**Issue by fdosa** [pik-copan/pyunicorn#238] opened 2024-09-03 07:07 UTC
Hi,

I'm experiencing problems when I try to install PyUnicorn through the Anaconda Prompt on Windows 11. Specifically, the affected file seems to be src_numerics.c.

I’ve pasted below the output when I try to install it with pip.
If it helps, here are the other packages that are installed:

- Python 3.12.4
- Cython 3.0.11
- h5netcdf 1.3.0
- python-igraph 0.11.6
- numpy 1.26.4
- scipy 1.14.1
- tqdm 4.66.5

Thanks for your help!

```c++
(tf_py312_env) C:\Users\fosaadm>pip install pyunicorn
Collecting pyunicorn
  Using cached pyunicorn-0.7.0.tar.gz (2.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.24 in c:\users\fosaadm\.conda\envs\tf_py312_env\lib\site-packages (from pyunicorn) (1.26.4)
Requirement already satisfied: scipy>=1.10 in c:\users\fosaadm\.conda\envs\tf_py312_env\lib\site-packages (from pyunicorn) (1.14.1)
Requirement already satisfied: igraph>=0.11 in c:\users\fosaadm\.conda\envs\tf_py312_env\lib\site-packages (from pyunicorn) (0.11.6)
Requirement already satisfied: tqdm>=4.66 in c:\users\fosaadm\.conda\envs\tf_py312_env\lib\site-packages (from pyunicorn) (4.66.5)
Requirement already satisfied: h5netcdf>=1.1 in c:\users\fosaadm\.conda\envs\tf_py312_env\lib\site-packages (from pyunicorn) (1.3.0)
Requirement already satisfied: h5py in c:\users\fosaadm\.conda\envs\tf_py312_env\lib\site-packages (from h5netcdf>=1.1->pyunicorn) (3.11.0)
Requirement already satisfied: packaging in c:\users\fosaadm\.conda\envs\tf_py312_env\lib\site-packages (from h5netcdf>=1.1->pyunicorn) (24.1)
Requirement already satisfied: texttable>=1.6.2 in c:\users\fosaadm\.conda\envs\tf_py312_env\lib\site-packages (from igraph>=0.11->pyunicorn) (1.7.0)
Requirement already satisfied: colorama in c:\users\fosaadm\.conda\envs\tf_py312_env\lib\site-packages (from tqdm>=4.66->pyunicorn) (0.4.6)
Building wheels for collected packages: pyunicorn
  Building wheel for pyunicorn (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyunicorn (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [143 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\pyunicorn
      copying src\pyunicorn\version.py -> build\lib.win-amd64-cpython-312\pyunicorn
      copying src\pyunicorn\__init__.py -> build\lib.win-amd64-cpython-312\pyunicorn
      creating build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\climate_data.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\climate_network.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\coupled_climate_network.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\coupled_tsonis.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\eventseries_climatenetwork.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\havlin.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\hilbert.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\map_plot.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\mutual_info.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\partial_correlation.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\rainfall.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\spearman.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\tsonis.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      copying src\pyunicorn\climate\__init__.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate
      creating build\lib.win-amd64-cpython-312\pyunicorn\core
      copying src\pyunicorn\core\cache.py -> build\lib.win-amd64-cpython-312\pyunicorn\core
      copying src\pyunicorn\core\data.py -> build\lib.win-amd64-cpython-312\pyunicorn\core
      copying src\pyunicorn\core\geo_grid.py -> build\lib.win-amd64-cpython-312\pyunicorn\core
      copying src\pyunicorn\core\geo_network.py -> build\lib.win-amd64-cpython-312\pyunicorn\core
      copying src\pyunicorn\core\grid.py -> build\lib.win-amd64-cpython-312\pyunicorn\core
      copying src\pyunicorn\core\interacting_networks.py -> build\lib.win-amd64-cpython-312\pyunicorn\core
      copying src\pyunicorn\core\netcdf_dictionary.py -> build\lib.win-amd64-cpython-312\pyunicorn\core
      copying src\pyunicorn\core\network.py -> build\lib.win-amd64-cpython-312\pyunicorn\core
      copying src\pyunicorn\core\resistive_network.py -> build\lib.win-amd64-cpython-312\pyunicorn\core
      copying src\pyunicorn\core\spatial_network.py -> build\lib.win-amd64-cpython-312\pyunicorn\core
      copying src\pyunicorn\core\__init__.py -> build\lib.win-amd64-cpython-312\pyunicorn\core
      creating build\lib.win-amd64-cpython-312\pyunicorn\eventseries
      copying src\pyunicorn\eventseries\event_series.py -> build\lib.win-amd64-cpython-312\pyunicorn\eventseries
      copying src\pyunicorn\eventseries\__init__.py -> build\lib.win-amd64-cpython-312\pyunicorn\eventseries
      creating build\lib.win-amd64-cpython-312\pyunicorn\funcnet
      copying src\pyunicorn\funcnet\coupling_analysis.py -> build\lib.win-amd64-cpython-312\pyunicorn\funcnet
      copying src\pyunicorn\funcnet\coupling_analysis_pure_python.py -> build\lib.win-amd64-cpython-312\pyunicorn\funcnet
      copying src\pyunicorn\funcnet\__init__.py -> build\lib.win-amd64-cpython-312\pyunicorn\funcnet
      creating build\lib.win-amd64-cpython-312\pyunicorn\timeseries
      copying src\pyunicorn\timeseries\cross_recurrence_plot.py -> build\lib.win-amd64-cpython-312\pyunicorn\timeseries
      copying src\pyunicorn\timeseries\inter_system_recurrence_network.py -> build\lib.win-amd64-cpython-312\pyunicorn\timeseries
      copying src\pyunicorn\timeseries\joint_recurrence_network.py -> build\lib.win-amd64-cpython-312\pyunicorn\timeseries
      copying src\pyunicorn\timeseries\joint_recurrence_plot.py -> build\lib.win-amd64-cpython-312\pyunicorn\timeseries
      copying src\pyunicorn\timeseries\recurrence_network.py -> build\lib.win-amd64-cpython-312\pyunicorn\timeseries
      copying src\pyunicorn\timeseries\recurrence_plot.py -> build\lib.win-amd64-cpython-312\pyunicorn\timeseries
      copying src\pyunicorn\timeseries\surrogates.py -> build\lib.win-amd64-cpython-312\pyunicorn\timeseries
      copying src\pyunicorn\timeseries\visibility_graph.py -> build\lib.win-amd64-cpython-312\pyunicorn\timeseries
      copying src\pyunicorn\timeseries\__init__.py -> build\lib.win-amd64-cpython-312\pyunicorn\timeseries
      creating build\lib.win-amd64-cpython-312\pyunicorn\utils
      copying src\pyunicorn\utils\mpi.py -> build\lib.win-amd64-cpython-312\pyunicorn\utils
      copying src\pyunicorn\utils\navigator.py -> build\lib.win-amd64-cpython-312\pyunicorn\utils
      copying src\pyunicorn\utils\__init__.py -> build\lib.win-amd64-cpython-312\pyunicorn\utils
      creating build\lib.win-amd64-cpython-312\pyunicorn\climate\_ext
      copying src\pyunicorn\climate\_ext\__init__.py -> build\lib.win-amd64-cpython-312\pyunicorn\climate\_ext
      creating build\lib.win-amd64-cpython-312\pyunicorn\core\_ext
      copying src\pyunicorn\core\_ext\types.py -> build\lib.win-amd64-cpython-312\pyunicorn\core\_ext
      copying src\pyunicorn\core\_ext\__init__.py -> build\lib.win-amd64-cpython-312\pyunicorn\core\_ext
      creating build\lib.win-amd64-cpython-312\pyunicorn\funcnet\_ext
      copying src\pyunicorn\funcnet\_ext\__init__.py -> build\lib.win-amd64-cpython-312\pyunicorn\funcnet\_ext
      creating build\lib.win-amd64-cpython-312\pyunicorn\timeseries\_ext
      copying src\pyunicorn\timeseries\_ext\__init__.py -> build\lib.win-amd64-cpython-312\pyunicorn\timeseries\_ext
      running egg_info
      writing src\pyunicorn.egg-info\PKG-INFO
      writing dependency_links to src\pyunicorn.egg-info\dependency_links.txt
      writing requirements to src\pyunicorn.egg-info\requires.txt
      writing top-level names to src\pyunicorn.egg-info\top_level.txt
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\arrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\arrayscalars.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\ndarrayobject.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\ndarraytypes.h won't be automatically included in the manifest: the path must be relative
      dependency C:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include\numpy\ufuncobject.h won't be automatically included in the manifest: the path must be relative
      reading manifest file 'src\pyunicorn.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'docs\source\tutorials\images'
      no previously-included directories found matching '**\.ipynb_checkpoints'
      adding license file 'LICENSE.txt'
      writing manifest file 'src\pyunicorn.egg-info\SOURCES.txt'
      copying src\pyunicorn\climate\_ext\numerics.pyx -> build\lib.win-amd64-cpython-312\pyunicorn\climate\_ext
      copying src\pyunicorn\climate\_ext\src_numerics.c -> build\lib.win-amd64-cpython-312\pyunicorn\climate\_ext
      copying src\pyunicorn\core\_ext\numerics.pyx -> build\lib.win-amd64-cpython-312\pyunicorn\core\_ext
      copying src\pyunicorn\core\_ext\src_numerics.c -> build\lib.win-amd64-cpython-312\pyunicorn\core\_ext
      copying src\pyunicorn\core\_ext\types.pxd -> build\lib.win-amd64-cpython-312\pyunicorn\core\_ext
      copying src\pyunicorn\funcnet\_ext\numerics.pyx -> build\lib.win-amd64-cpython-312\pyunicorn\funcnet\_ext
      copying src\pyunicorn\timeseries\_ext\numerics.pyx -> build\lib.win-amd64-cpython-312\pyunicorn\timeseries\_ext
      copying src\pyunicorn\timeseries\_ext\src_numerics.c -> build\lib.win-amd64-cpython-312\pyunicorn\timeseries\_ext
      running build_ext
      building 'pyunicorn.climate._ext.numerics' extension
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      creating build\temp.win-amd64-cpython-312\Release\src
      creating build\temp.win-amd64-cpython-312\Release\src\pyunicorn
      creating build\temp.win-amd64-cpython-312\Release\src\pyunicorn\climate
      creating build\temp.win-amd64-cpython-312\Release\src\pyunicorn\climate\_ext
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -D_GNU_SOURCE -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Isrc/pyunicorn/climate/_ext -IC:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include -IC:\Users\fosaadm\.conda\envs\tf_py312_env\include -IC:\Users\fosaadm\.conda\envs\tf_py312_env\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc/pyunicorn/climate/_ext/numerics.c /Fobuild\temp.win-amd64-cpython-312\Release\src/pyunicorn/climate/_ext/numerics.obj /O2
      numerics.c
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\fosaadm\.conda\envs\tf_py312_env\libs /LIBPATH:C:\Users\fosaadm\.conda\envs\tf_py312_env /LIBPATH:C:\Users\fosaadm\.conda\envs\tf_py312_env\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" /EXPORT:PyInit_numerics build\temp.win-amd64-cpython-312\Release\src/pyunicorn/climate/_ext/numerics.obj /OUT:build\lib.win-amd64-cpython-312\pyunicorn\climate\_ext\numerics.cp312-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-312\Release\src/pyunicorn/climate/_ext\numerics.cp312-win_amd64.lib
         Creating library build\temp.win-amd64-cpython-312\Release\src/pyunicorn/climate/_ext\numerics.cp312-win_amd64.lib and object build\temp.win-amd64-cpython-312\Release\src/pyunicorn/climate/_ext\numerics.cp312-win_amd64.exp
      Generating code
      Finished generating code
      building 'pyunicorn.core._ext.numerics' extension
      creating build\temp.win-amd64-cpython-312\Release\src\pyunicorn\core
      creating build\temp.win-amd64-cpython-312\Release\src\pyunicorn\core\_ext
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -D_GNU_SOURCE -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Isrc/pyunicorn/core/_ext -IC:\Users\fosaadm\AppData\Local\Temp\pip-build-env-n31vd7b0\overlay\Lib\site-packages\numpy\_core\include -IC:\Users\fosaadm\.conda\envs\tf_py312_env\include -IC:\Users\fosaadm\.conda\envs\tf_py312_env\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc/pyunicorn/core/_ext/numerics.c /Fobuild\temp.win-amd64-cpython-312\Release\src/pyunicorn/core/_ext/numerics.obj /O2
      numerics.c
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(121): error C2143: syntax error: missing ')' before 'constant'
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(121): error C2371: '_FCbuild': redefinition; different basic types
      C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt\complex.h(151): note: see declaration of '_FCbuild'
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(121): error C2143: syntax error: missing ';' before 'constant'
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(121): error C2059: syntax error: ')'
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(121): error C2106: '=': left operand must be l-value
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(125): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(125): error C2106: '=': left operand must be l-value
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(134): warning C4244: '+=': conversion from 'double' to 'int', possible loss of data
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(131): error C2106: '+=': left operand must be l-value
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(152): error C2143: syntax error: missing ')' before 'constant'
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(152): error C2143: syntax error: missing ';' before 'constant'
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(152): error C2059: syntax error: ')'
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(152): error C2106: '=': left operand must be l-value
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(156): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(156): error C2106: '=': left operand must be l-value
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(160): warning C4244: '+=': conversion from 'double' to 'int', possible loss of data
      C:\Users\fosaadm\AppData\Local\Temp\pip-install-d0p3mfkz\pyunicorn_db38825810d94570b3c500667037cb0a\src\pyunicorn\core\_ext\src_numerics.c(159): error C2106: '+=': left operand must be l-value
      src/pyunicorn/core/_ext/numerics.c(29778): warning C4244: '=': conversion from 'Py_ssize_t' to 'long', possible loss of data
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyunicorn
Failed to build pyunicorn
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyunicorn)
``` `

**Comment by fkuehlein** [comment] 2024-09-03 09:51
Hi @fdosa,

thank you for reporting this! 

I will have a closer look into it later this week. In the meantime, could you try to install the current development version via `pip install git+https://github.com/pik-copan/pyunicorn.git` and let me know whether you run into the same problem?

Cheers

**Comment by fkuehlein** [comment] 2024-09-05 13:55
Unfortunately I cannot reproduce this, and apparently I am not enough of an expert in C to make sense of the error message reported in the OP. 

However, if this problem should persist with the current development version, it should be resolved by finally porting these remaining C modules to Cython, as advocated in #230. Such errors would then be revealed by our CI at an earlier stage.

**Comment by fdosa** [comment] 2024-09-12 07:24
Hi,

Thank you for your prompt response and suggestions. I followed your advice and installed the current development version from the GitHub repository (v0.8.0). I was able to install it successfully on Windows 11, and the test code I ran worked perfectly.

I appreciate your efforts in looking into the issue, and I understand the complexities related to the C modules. Should I encounter the same problem in the future, I'll make sure to report it. It's also great to know that the transition to Cython is being considered and may help catch these issues earlier.

Thank you again for your support, and I look forward to any future updates!

**Comment by fkuehlein** [comment] 2024-09-12 07:53
Hi @fdosa,

thank you for your reply. Indeed, having the C modules compile on Windows had been causing us problems in the past (see e.g. #159, #160). Therefore especially, I'm glad to hear that the issue did not persist with the current development version! Please consider my last comment more as a note to myself and our team for the sake of documentation than a direct reply to your post, hence the sober formulation. Anyway, I am happy to preannounce that we will officially release the new version `v0.8.0` next week, so it will also be available via `pip` from then on!

**Closed by fkuehlein** 2024-09-12 07:53 UTC
Labels: installation
