### ISSUE TITLE
 ModuleNotFoundError: No module named 'pyunicorn.core._ext.numerics'

### ISSUE THREAD

**Issue by sofiafarina** [pik-copan/pyunicorn#130] opened 2019-11-06 22:24 UTC
Hello, 

when I try to run the climate tutorial I get the following error:

    from ._ext.numerics import _local_cliquishness_4thorder, \
ModuleNotFoundError: No module named 'pyunicorn.core._ext.numerics'

There's the numerics file but with a different extension.
What should I do? 

Thank you very much.

**Comment by jkroenke** [comment] 2019-11-07 13:55
How did you install pyunicorn? If you directly download it from the source you have to cythonize the _ext/numerics.pyx files yourself, e.g., by running 'python setup.py build'. After that, there should be corresponding _ext/numerics.c files.

**Comment by sofiafarina** [comment] 2019-11-07 14:24
Thank you very much for your help.
I cythonized it as you suggested and I have now the numerics.c file in the core folder but I still get the error:

> 
> from pyunicorn import climate
>   File "/Users/Sofia/Desktop/pyunicorn-master/pyunicorn/__init__.py", line 46, in <module>
>     from .core import *
>   File "/Users/Sofia/Desktop/pyunicorn-master/pyunicorn/core/__init__.py", line 44, in <module>
>     from .network import Network, NetworkError, nz_coords, cached_const
>   File "/Users/Sofia/Desktop/pyunicorn-master/pyunicorn/core/network.py", line 52, in <module>
>     from ._ext.numerics import _local_cliquishness_4thorder, \
> ModuleNotFoundError: No module named 'pyunicorn.core._ext.numerics'

Thank you, 
Sofia

**Comment by jkroenke** [comment] 2019-11-08 11:00
What python and cython versions do you use?

**Comment by sofiafarina** [comment] 2019-11-08 11:06
Python version 3.6.4 
Cython version 0.27.3

thank you!

**Comment by sofiafarina** [comment] 2019-11-08 11:09
I also updated them to the latest versions but I still get the error.

**Comment by jkroenke** [comment] 2019-11-08 14:57
Ok, the problem is that the .pyx files are cythonized to .c files within the folder. However, the object files created by the C compiler are only generated into the pyunicorn/build directory. When you copy the corresponding .so file from pyunicorn/build/.../_ext/numerics to your original directory the import of the cython modules should work. I'm still thinking of a better solution without manually copying.

**Comment by sofiafarina** [comment] 2019-11-09 15:00
Okay, sorry but I am not sure: which file do I have to copy and where?
Thank you again!

**Comment by sofiafarina** [comment] 2019-11-09 15:11
I mean, in the searched folder there are numerics.c and numerics.pyx..

<img width="769" alt="Schermata 2019-11-09 alle 16 10 01" src="https://user-images.githubusercontent.com/20513442/68530732-71fab200-030b-11ea-91f5-4d919950ffce.png">

**Comment by jkroenke** [comment] 2019-11-11 10:48
When you run 'python setup.py build' a build folder should be generated in the top-level pyunicorn folder. In that folder you should find .so files in the corresponding */_ext/numerics folders. If you copy these files into your source directory, the pyunicorn import should work.

**Comment by sofiafarina** [comment] 2019-11-12 11:28
I copied the numerics.o file into my source directory but I still get the same error 
maybe it is because it is looking for .../numerics (so there's no extension) but the files are: numerics.c, numerics.pyx, numerics.o (this last one copied from the build folder)..?

Thank you

**Comment by hadware** [comment] 2020-03-10 19:09
I have the same error here on a Python3.7 conda environment. I'll try to find some fix.

**Comment by seongsilheo** [comment] 2020-06-04 07:39
Hi, I also can not find the .so file. I can just see numerics.o from the build folder. I also copy that file to my directory. So the file are : numerics.c, numerics.pyx, numerics.o
I still have the ModuleNotFoundError issue. (No module named pyunicorn.core._ext.numerics)

Anyone knows how to fix this issue?
Thank you very much.

**Comment by Mattyboi123** [comment] 2020-06-26 21:13
@seongsilheo have you been able to get this working yet?  I still can not :(

**Comment by lenas95** [comment] 2022-03-08 15:08
Hi, if the issue is still pending I tried to mimic the issue as I had the same problem. 
I solved it by:
 -  Running python setup.py build (if that does not work try python3 setup.py build)
 - There should be a now a folder build in the upper level of your directory (e.g. where the tests and tools folder is)
 - As I am using Linux in my ./pyunicorn/build/lib.linux-x86_64-3.8/pyunicorn/core/_ext Folder there is a file named numerics.cpython-38-x86_64-linux-gnu.so )
 - Go into your lower level directory of pyunicorn (e.g. where climate or core folder is located). In my case this is pyunicorn/pyunicorn/
 - Copy the .so file into your core folder. In my case that is ./ pyunicorn/pyunicorn/core/_ext . 
 - Then _ext/numerics is found
 
Please comment on further issues or if this resolved the problem
Greetings

**Comment by ntfrgl** [comment] 2022-04-08 05:20
Thank you for reporting this issue, and please accept our apologies for our delay in providing a rigorous solution. This set of problems should be fully resolved with the commit linked above, which will be reflected in an upcoming new release including official wheels. I'm tentatively closing this ticket, but please let us know in case you have any trouble installing `pyunicorn` from the current `master` branch, in which case we will attempt to find a solution as quickly as possible.

Cython is now declared as a build dependency, which means that your Python package manager (e.g., `pip`) is responsible for automatically providing the Cython compiler without any user intervention. After the package installation process is completed, Cython is **not** required as a runtime dependency. The version information is now retrieved via `importlib.metadata` from the Python standard library.

**Closed by ntfrgl** 2022-04-08 05:20 UTC
