### ISSUE TITLE
error when installing

### ISSUE THREAD

**Issue by Palaeocortex** [pik-copan/pyunicorn#122] opened 2019-04-09 22:21 UTC
I can't install the newest release 0.6.0.post1 with Python3:
```
  File "./setup.py", line 22
    f'pyunicorn.{pkg}._ext.numerics',
                                   ^
SyntaxError: invalid syntax
```
The command is 
sudo python3 ./setup.py install
The same error occurs with pip.

**Comment by jdonges** [comment] 2019-04-10 07:56
Dear Cristian,

we tested the install via setup.py and pip on different machines running Python3 on Mac OSX (Mojave), Linux and Windows and it works for us.

Please check that you actually have a Python3 environment installed and linked as the standard Python interpreter on your system. 

Cheers,
Jonathan

**Comment by jdonges** [comment] 2019-04-12 12:38
We have tracked down the bug. What you can do now is download the latest development version at: https://github.com/pik-copan/pyunicorn/archive/master.zip <https://github.com/pik-copan/pyunicorn/archive/master.zip>

Then install cython and then install pyunicorn via setup.py which will compile the C extensions on your machine.

**Comment by Palaeocortex** [comment] 2019-04-14 23:05
Dear Jonathan,
Thanks a lot for debugging! I am still getting the same error message:
```
  File "setup.py", line 34
    f'pyunicorn.{pkg}._ext.numerics',
                                   ^
SyntaxError: invalid syntax
```
Am I doing something wrong? Python3, cython and all dependencies are installed (otherwise it would complain at an earlier line). Against what is this line linking? I am not familiar with installation scripts.

**Comment by ntfrgl** [comment] 2019-04-15 01:59
@jdonges This seems to be a different problem.Looking at the error message, I would suspect that

**Comment by ntfrgl** [comment] 2019-04-15 02:10
@jdonges This seems to be a different problem.
@Palaeocortex These lines are defining the `Cython` extensions.

The only simple explanation for this error message that I can think of is that `setup.py` is in fact being executed by `Python 2`, and therefore the `Python 3` string formatting syntax `f"{}"` is seen as invalid. This might be caused by any number of environment configuration issues on your machine. Please falsify by adding the following lines to the beginning of `setup.py`:
```
import sys
print(sys.version)
```

**Comment by nseyyednejad** [comment] 2019-04-18 19:22
Dear Jonathan,
I tried to install Pyunicorn in python3. but, mpl_toolkits.basemap is in python2. what should I do for installing this package? thanks for any suggestion.

**Comment by jdonges** [comment] 2019-04-20 08:25
Basemap is an optional dependency. Hence, you don't need it for running most of pyunicorn's functions.

**Comment by ntfrgl** [comment] 2022-04-08 05:17
Thank you for reporting this issue, and please accept our apologies for our delay in providing a rigorous solution. This set of problems should be fully resolved with the commit linked above, which will be reflected in an upcoming new release including official wheels. I'm tentatively closing this ticket, but please let us know in case you have any trouble installing `pyunicorn` from the current `master` branch, in which case we will attempt to find a solution as quickly as possible.

Cython is now declared as a build dependency, which means that your Python package manager (e.g., `pip`) is responsible for automatically providing the Cython compiler without any user intervention. After the package installation process is completed, Cython is **not** required as a runtime dependency. The version information is now retrieved via `importlib.metadata` from the Python standard library.

**Closed by ntfrgl** 2022-04-08 05:17 UTC
