### ISSUE TITLE
ModuleNotFoundError: No module named 'setup'

### ISSUE THREAD

**Issue by kamblesamadhan** [pik-copan/pyunicorn#137] opened 2020-02-25 11:30 UTC
I am using ubuntu 18.04 LTS. I installed pyunicorn by only one line: "sudo pip3 install pyunicorn". 
I tried simple code mentioned in the introduction of the documentation but I am getting the following error: 

   from pyunicorn.timeseries import RecurrenceNetwork
  File "/usr/local/lib/python3.6/dist-packages/pyunicorn/__init__.py", line 43, in <module>
    from setup import __version__
ModuleNotFoundError: No module named 'setup'

**Comment by jkroenke** [comment] 2020-02-25 11:56
Duplicate of issue #129. Deleting line 43 from the file should solve the problem. The version number of pyunicorn will not be available with pyunicorn.__version__ then.

**Comment by kamblesamadhan** [comment] 2020-02-25 12:17
Thanks jkroenke. But pyunicorn in my ubuntu 18.04 is not located at site-packages folder but at dist-packages folder and unfortunately I am not able to find it.

**Comment by jkroenke** [comment] 2020-02-25 12:20
Your pyunicorn/init.py should be located at "/usr/local/lib/python3.6/dist-packages/pyunicorn/init.py" as it says in your error message above.

**Comment by kamblesamadhan** [comment] 2020-02-25 12:38
> Your pyunicorn/init.py should be located at "/usr/local/lib/python3.6/dist-packages/pyunicorn/init.py" as it says in your error message above.

This may be a very silly question. Actually ,how to open that init.py file?

I tried:

hp@sam:/usr/local/lib/python3.6/dist-packages$ cd pyunicorn
hp@sam:/usr/local/lib/python3.6/dist-packages/pyunicorn$ ls
climate      core         funcnet      __pycache__  utils
conftest.py  eventseries  __init__.py  timeseries
hp@sam:/usr/local/lib/python3.6/dist-packages/pyunicorn$ cd init.py
bash: cd: init.py: No such file or directory
hp@sam:/usr/local/lib/python3.6/dist-packages/pyunicorn$ cd __init__.py
bash: cd: __init__.py: Not a directory
hp@sam:/usr/local/lib/python3.6/dist-packages/pyunicorn$ __init__.py
__init__.py: command not found

Also, using file manager, dist-packages folder itself is not showing.Only site-packages folder is there as I already mentioned.

**Comment by kamblesamadhan** [comment] 2020-02-25 12:52
> Your pyunicorn/init.py should be located at "/usr/local/lib/python3.6/dist-packages/pyunicorn/init.py" as it says in your error message above.

I opened the init.py file in gedit but it says format is "read only" and you do not have permission to save any changes. What should I do?

**Comment by kamblesamadhan** [comment] 2020-02-25 12:58
> Your pyunicorn/init.py should be located at "/usr/local/lib/python3.6/dist-packages/pyunicorn/init.py" as it says in your error message above.

Thanks again!

**Closed** 2020-02-25 14:17 UTC

**Comment by qinghualiurong** [comment] 2021-12-17 05:12
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-40-de2a66afaf2c> in <module>
----> 1 import pyunicorn as pyu

~/anaconda3/lib/python3.7/site-packages/pyunicorn/__init__.py in <module>
     41 import sys
     42 
---> 43 from setup import __version__
     44 
     45 from .utils import mpi

ModuleNotFoundError: No module named 'setup'
