### ISSUE TITLE
module 'numpy' has no attribute 'int'

### ISSUE THREAD

**Issue by yuxuan55** [pik-copan/pyunicorn#207] opened 2023-12-12 17:49 UTC
when I use numpy==1.24 
it shows: AttributeError: module 'numpy' has no attribute 'int'

and when I use numpy==1.20
it shows: ImportError: numpy.core.multiarray failed to import
 
How can I fix this?

**Comment by ntfrgl** [comment] 2023-12-12 20:10
I'm closing this issue as a duplicate of #189. Please read the answer there.

**Closed by ntfrgl** 2023-12-12 20:10 UTC
