### ISSUE TITLE
Unable to install pyunicorn  in google collab and windows 10 using anacoda

### ISSUE THREAD

**Issue by jyotiyadav94** [pik-copan/pyunicorn#159] opened 2022-04-10 16:17 UTC
Hi,

I have installed the pyunicorn in the google collab using the 
!pip install pyunicorn. But I see the below error after installing it.

[
![image](https://user-images.githubusercontent.com/72126242/162628832-ddcf4395-0bf9-4ac5-8b9a-8ba8392e3db7.png)
](url)

Also i tried installing the package in windows 10. using the anaconda in the base environment the below packages 
But it doesn't solve my problem i still get the import error. I would like to know how can i use the pyunicorn  library.Please let me know the possible solution to use the same

![image](https://user-images.githubusercontent.com/72126242/162629009-b8b00667-a9e1-485e-9330-5e52be2973cd.png)

![image](https://user-images.githubusercontent.com/72126242/162628978-ad8370ff-858b-4e7f-b9b0-62a270597d02.png)

**Comment by ntfrgl** [comment] 2022-04-10 22:39
Hi @jyotiyadav94,

This is a known issue with the previous version, which was resolved recently in a6c4c83. Since these changes are not yet reflected in an official release on PyPI, please try installing from source, i.e., check out the current `master` branch and execute:
```
pip install .
```
I'm tentatively closing this ticket, but please let us know in case you encounter any issues with this approach.

**Closed by ntfrgl** 2022-04-10 22:39 UTC

**Comment by xandie985** [comment] 2022-04-13 16:15
Hi [Boyan Beronov](https://github.com/ntfrgl)

I also face a similar issue. I have installed all the requirements as below. When I tried to run the project with the same environment in windows machine visual studio code I see the error .It has a setup.py file as well in the code. But it still has the error. 

![image](https://user-images.githubusercontent.com/18325219/163224348-0fa312a7-1ee2-457b-a220-c9aaf3fc1497.png)



 Even after installing the requirements, it gives this error it has been 5 days since i am trying to work on this library. Can you please suggest me something?

I tried to run this code which uses this library - https://github.com/BUAA-WJR/PriceGraph

Requirements :

![image](https://user-images.githubusercontent.com/18325219/163223050-893a489c-a594-42e7-aaa5-3454c52d8588.png)

![image](https://user-images.githubusercontent.com/18325219/163223176-7eebf3d4-526a-44be-ba3a-51b44e540767.png)

**Comment by ntfrgl** [comment] 2022-04-13 22:16
Hi @xandie985,

The answer to your question is exactly the same as the one I gave in my previous comment. In particular, in [your screenshot](https://user-images.githubusercontent.com/18325219/163223176-7eebf3d4-526a-44be-ba3a-51b44e540767.png) you are using a wheel built from an old version with a known installation problem. If you're interested in successfully installing the library without waiting until the next official release, then you should try to follow my instructions above.

**Comment by jyotiyadav94** [comment] 2022-04-14 10:17
Hi @ntfrgl 

I followed the steps mentioned by you. I downloaded the repo master branch.

Since I am using the windows I perform these two steps :

![image](https://user-images.githubusercontent.com/72126242/163364654-23e1c398-92b9-4756-842e-edda619626aa.png)

Then i get the below errors 
The wheels are getting failed 

![image](https://user-images.githubusercontent.com/72126242/163364505-1eb4a27a-aa89-40ea-9ce9-e31f7f314e5a.png)

![image](https://user-images.githubusercontent.com/72126242/163364763-e1393392-819d-4a27-90fc-8c45953afdfa.png)

![image](https://user-images.githubusercontent.com/72126242/163364813-43a11b05-5e9e-405a-b8a5-13770f8f42e6.png)

Is it possible to schedule the call if you are free? It would be great if you can provide an appointment.

**Comment by jyotiyadav94** [comment] 2022-04-14 11:08
Also, I tried again to install again the wheel file. 
Python version: 3.7.0
windows 10 * 64
https://github.com/nikfrlv/pyunicorn-windows-whl

I see the below error 

![image](https://user-images.githubusercontent.com/72126242/163379197-9f7b4ea0-931d-4f88-9df8-1c5537d23373.png)


![image](https://user-images.githubusercontent.com/72126242/163379259-2ce07086-d872-4ec1-8aac-eab1a10d7628.png)

**Comment by jyotiyadav94** [comment] 2022-04-14 16:43
okay @ntfrgl 

I was able to fix the issue just by deleting the file C:\Users\jyoti\anaconda3\envs\pyunicornLib\Lib\site-packages\pyunicorn
__init__.py file as a workaround I was able to run my test properly. This resolved my issue 

Thanks for your time.

**Comment by ntfrgl** [comment] 2022-04-14 19:14
Hi @jyotiyadav94, I'm glad that you've found a workaround, even though it's using the old version of `pyunicorn`.

In both of your attempts above, you can see that the problem is the following:
```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```
This is a general issue with compiled Python packages on Windows, and not specific to `pyunicorn`. As you can see by searching on the web, many people have faced this same issue and were able to resolve it simply by following the instructions provided within the error message. For a more detailed explanation, see, e.g., [this video](https://www.youtube.com/watch?v=rcI1_e38BWs).

I don't have access to a Windows machine and can't test it, but if you could let us know whether this solution works for you with the latest `master` version, then we could improve our installation instructions to help other Windows users.
