### ISSUE TITLE
Still exists:   No module named 'setup' (v0.6.1) #129

### ISSUE THREAD

**Issue by jjv5** [pik-copan/pyunicorn#139] opened 2020-03-25 17:52 UTC
Install of pyunicorn with python 3.7 using stable release 0.6.1 still produces this error:

`>>> print(sys.version)
3.7.7 (default, Mar 24 2020, 18:54:20) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
>>> import pyunicorn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/programs/x86_64-linux/pyunicorn/0.6.1/lib/python3.7/site-packages/pyunicorn/__init__.py", line 43, in <module>
    from setup import __version__
ModuleNotFoundError: No module named 'setup'
>>> `

**Comment by jkroenke** [comment] 2020-03-31 12:58
Duplicate of issue #129. The issue should be solved with commit bd490ad47c12f829a9773abc622b0d3c306d98e6 and will be closed when the open PR is merged.

**Closed by jkroenke** 2020-03-31 12:58 UTC
