### ISSUE TITLE
Failed building wheel for pyunicorn while installing

### ISSUE THREAD

**Issue by Sumit-Mukherjee** [pik-copan/pyunicorn#208] opened 2023-12-14 06:56 UTC
Unable to install pyunicorn in cray linux with python 3.9.12. Wheel 0.42.0 is installed already. The terminal output is as follows:

(py39_pyunicorn) ayantika@elogin03:~/Sumit> pip install pyunicorn 
Collecting pyunicorn
  Using cached pyunicorn-0.6.1.tar.gz (881 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.14 in /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/lib/python3.9/site-packages (from pyunicorn) (1.23.1)
Requirement already satisfied: scipy>=1.0 in /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/lib/python3.9/site-packages (from pyunicorn) (1.8.1)
Requirement already satisfied: python-igraph>=0.7 in /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/lib/python3.9/site-packages (from pyunicorn) (0.11.3)
Requirement already satisfied: igraph==0.11.3 in /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/lib/python3.9/site-packages (from python-igraph>=0.7->pyunicorn) (0.11.3)
Requirement already satisfied: texttable>=1.6.2 in /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/lib/python3.9/site-packages (from igraph==0.11.3->python-igraph>=0.7->pyunicorn) (1.7.0)
Building wheels for collected packages: pyunicorn
  Building wheel for pyunicorn (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [151 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-39
      creating build/lib.linux-x86_64-cpython-39/pyunicorn
      copying pyunicorn/conftest.py -> build/lib.linux-x86_64-cpython-39/pyunicorn
      copying pyunicorn/__init__.py -> build/lib.linux-x86_64-cpython-39/pyunicorn
      creating build/lib.linux-x86_64-cpython-39/pyunicorn/core
      copying pyunicorn/core/geo_network.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/core
      copying pyunicorn/core/data.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/core
      copying pyunicorn/core/grid.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/core
      copying pyunicorn/core/network.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/core
      copying pyunicorn/core/resistive_network.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/core
      copying pyunicorn/core/netcdf_dictionary.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/core
      copying pyunicorn/core/interacting_networks.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/core
      copying pyunicorn/core/__init__.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/core
      creating build/lib.linux-x86_64-cpython-39/pyunicorn/core/_ext
      copying pyunicorn/core/_ext/__init__.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/core/_ext
      creating build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/hilbert.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/havlin.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/climate_data.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/tsonis.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/map_plots.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/climate_network.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/mutual_info.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/coupled_climate_network.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/spearman.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/__init__.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/eventsynchronization_climatenetwork.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/partial_correlation.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/coupled_tsonis.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      copying pyunicorn/climate/rainfall.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate
      creating build/lib.linux-x86_64-cpython-39/pyunicorn/climate/_ext
      copying pyunicorn/climate/_ext/__init__.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/climate/_ext
      creating build/lib.linux-x86_64-cpython-39/pyunicorn/timeseries
      copying pyunicorn/timeseries/joint_recurrence_plot.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/timeseries
      copying pyunicorn/timeseries/recurrence_network.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/timeseries
      copying pyunicorn/timeseries/inter_system_recurrence_network.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/timeseries
      copying pyunicorn/timeseries/surrogates.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/timeseries
      copying pyunicorn/timeseries/recurrence_plot.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/timeseries
      copying pyunicorn/timeseries/__init__.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/timeseries
      copying pyunicorn/timeseries/joint_recurrence_network.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/timeseries
      copying pyunicorn/timeseries/visibility_graph.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/timeseries
      copying pyunicorn/timeseries/cross_recurrence_plot.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/timeseries
      creating build/lib.linux-x86_64-cpython-39/pyunicorn/timeseries/_ext
      copying pyunicorn/timeseries/_ext/__init__.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/timeseries/_ext
      creating build/lib.linux-x86_64-cpython-39/pyunicorn/funcnet
      copying pyunicorn/funcnet/coupling_analysis_pure_python.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/funcnet
      copying pyunicorn/funcnet/coupling_analysis.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/funcnet
      copying pyunicorn/funcnet/__init__.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/funcnet
      copying pyunicorn/funcnet/event_synchronization.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/funcnet
      creating build/lib.linux-x86_64-cpython-39/pyunicorn/funcnet/_ext
      copying pyunicorn/funcnet/_ext/__init__.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/funcnet/_ext
      creating build/lib.linux-x86_64-cpython-39/pyunicorn/eventseries
      copying pyunicorn/eventseries/eca.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/eventseries
      creating build/lib.linux-x86_64-cpython-39/pyunicorn/utils
      copying pyunicorn/utils/navigator.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/utils
      copying pyunicorn/utils/__init__.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/utils
      copying pyunicorn/utils/mpi.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/utils
      creating build/lib.linux-x86_64-cpython-39/pyunicorn/utils/progressbar
      copying pyunicorn/utils/progressbar/compat.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/utils/progressbar
      copying pyunicorn/utils/progressbar/widgets.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/utils/progressbar
      copying pyunicorn/utils/progressbar/__init__.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/utils/progressbar
      copying pyunicorn/utils/progressbar/progressbar.py -> build/lib.linux-x86_64-cpython-39/pyunicorn/utils/progressbar
      running build_ext
      building 'pyunicorn.climate._ext.numerics' extension
      creating build/temp.linux-x86_64-cpython-39
      creating build/temp.linux-x86_64-cpython-39/pyunicorn
      creating build/temp.linux-x86_64-cpython-39/pyunicorn/climate
      creating build/temp.linux-x86_64-cpython-39/pyunicorn/climate/_ext
      gcc -pthread -B /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include -fPIC -O2 -isystem /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include -fPIC -I/home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/lib/python3.9/site-packages/numpy/core/include -I/home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9 -c pyunicorn/climate/_ext/numerics.c -o build/temp.linux-x86_64-cpython-39/pyunicorn/climate/_ext/numerics.o -O3 -std=c99
      In file included from /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1948:0,
                       from /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                       from /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:5,
                       from pyunicorn/climate/_ext/numerics.c:456:
      /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
       #warning "Using deprecated NumPy API, disable it with " \
        ^
      In file included from pyunicorn/climate/_ext/numerics.c:458:0:
      pyunicorn/climate/_ext/src_numerics.c: In function ‘_cython_calculate_mutual_information’:
      pyunicorn/climate/_ext/src_numerics.c:35:19: warning: assignment from incompatible pointer type [enabled by default]
               p_anomaly = anomaly + in_samples;
                         ^
      pyunicorn/climate/_ext/numerics.c: In function ‘__Pyx_ParseOptionalKeywords’:
      pyunicorn/climate/_ext/numerics.c:5518:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated (declared at /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9/cpython/unicodeobject.h:446) [-Wdeprecated-declarations]
                           (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
                           ^
      pyunicorn/climate/_ext/numerics.c:5518:21: warning: ‘PyUnicode_AsUnicode’ is deprecated (declared at /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9/cpython/unicodeobject.h:580) [-Wdeprecated-declarations]
      pyunicorn/climate/_ext/numerics.c:5518:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated (declared at /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9/cpython/unicodeobject.h:446) [-Wdeprecated-declarations]
      pyunicorn/climate/_ext/numerics.c:5518:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated (declared at /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9/cpython/unicodeobject.h:446) [-Wdeprecated-declarations]
      pyunicorn/climate/_ext/numerics.c:5518:21: warning: ‘PyUnicode_AsUnicode’ is deprecated (declared at /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9/cpython/unicodeobject.h:580) [-Wdeprecated-declarations]
      pyunicorn/climate/_ext/numerics.c:5518:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated (declared at /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9/cpython/unicodeobject.h:446) [-Wdeprecated-declarations]
      pyunicorn/climate/_ext/numerics.c:5534:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated (declared at /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9/cpython/unicodeobject.h:446) [-Wdeprecated-declarations]
                               (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
                               ^
      pyunicorn/climate/_ext/numerics.c:5534:25: warning: ‘PyUnicode_AsUnicode’ is deprecated (declared at /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9/cpython/unicodeobject.h:580) [-Wdeprecated-declarations]
      pyunicorn/climate/_ext/numerics.c:5534:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated (declared at /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9/cpython/unicodeobject.h:446) [-Wdeprecated-declarations]
      pyunicorn/climate/_ext/numerics.c:5534:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated (declared at /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9/cpython/unicodeobject.h:446) [-Wdeprecated-declarations]
      pyunicorn/climate/_ext/numerics.c:5534:25: warning: ‘PyUnicode_AsUnicode’ is deprecated (declared at /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9/cpython/unicodeobject.h:580) [-Wdeprecated-declarations]
      pyunicorn/climate/_ext/numerics.c:5534:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated (declared at /home/cccr/ayantika/anaconda3/envs/py39_pyunicorn/include/python3.9/cpython/unicodeobject.h:446) [-Wdeprecated-declarations]
      pyunicorn/climate/_ext/numerics.c: In function ‘__Pyx__ExceptionSave’:
      pyunicorn/climate/_ext/numerics.c:6421:19: error: ‘PyThreadState’ has no member named ‘exc_type’
           *type = tstate->exc_type;
                         ^
      pyunicorn/climate/_ext/numerics.c:6422:20: error: ‘PyThreadState’ has no member named ‘exc_value’
           *value = tstate->exc_value;
                          ^
      pyunicorn/climate/_ext/numerics.c:6423:17: error: ‘PyThreadState’ has no member named ‘exc_traceback’
           *tb = tstate->exc_traceback;
                       ^
      pyunicorn/climate/_ext/numerics.c: In function ‘__Pyx__ExceptionReset’:
      pyunicorn/climate/_ext/numerics.c:6430:22: error: ‘PyThreadState’ has no member named ‘exc_type’
           tmp_type = tstate->exc_type;
                            ^
      pyunicorn/climate/_ext/numerics.c:6431:23: error: ‘PyThreadState’ has no member named ‘exc_value’
           tmp_value = tstate->exc_value;
                             ^
      pyunicorn/climate/_ext/numerics.c:6432:20: error: ‘PyThreadState’ has no member named ‘exc_traceback’
           tmp_tb = tstate->exc_traceback;
                          ^
      pyunicorn/climate/_ext/numerics.c:6433:11: error: ‘PyThreadState’ has no member named ‘exc_type’
           tstate->exc_type = type;
                 ^
      pyunicorn/climate/_ext/numerics.c:6434:11: error: ‘PyThreadState’ has no member named ‘exc_value’
           tstate->exc_value = value;
                 ^
      pyunicorn/climate/_ext/numerics.c:6435:11: error: ‘PyThreadState’ has no member named ‘exc_traceback’
           tstate->exc_traceback = tb;
                 ^
      pyunicorn/climate/_ext/numerics.c: In function ‘__Pyx__GetException’:
      pyunicorn/climate/_ext/numerics.c:6490:22: error: ‘PyThreadState’ has no member named ‘exc_type’
           tmp_type = tstate->exc_type;
                            ^
      pyunicorn/climate/_ext/numerics.c:6491:23: error: ‘PyThreadState’ has no member named ‘exc_value’
           tmp_value = tstate->exc_value;
                             ^
      pyunicorn/climate/_ext/numerics.c:6492:20: error: ‘PyThreadState’ has no member named ‘exc_traceback’
           tmp_tb = tstate->exc_traceback;
                          ^
      pyunicorn/climate/_ext/numerics.c:6493:11: error: ‘PyThreadState’ has no member named ‘exc_type’
           tstate->exc_type = local_type;
                 ^
      pyunicorn/climate/_ext/numerics.c:6494:11: error: ‘PyThreadState’ has no member named ‘exc_value’
           tstate->exc_value = local_value;
                 ^
      pyunicorn/climate/_ext/numerics.c:6495:11: error: ‘PyThreadState’ has no member named ‘exc_traceback’
           tstate->exc_traceback = local_tb;
                 ^
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyunicorn
  Running setup.py clean for pyunicorn
Failed to build pyunicorn
ERROR: Could not build wheels for pyunicorn, which is required to install pyproject.toml-based projects
(py39_pyunicorn) ayantika@elogin03:~/Sumit>

**Comment by ntfrgl** [comment] 2023-12-14 07:13
I'm closing this issue as a duplicate of #154. You are facing a known problem with the latest official release `v0.6.1` (June 2019). While we are planning a new official release early next year, if you would like to use the package now, I strongly recommend installing the current development version from the `master` branch, see https://github.com/pik-copan/pyunicorn#installation.

**Closed by ntfrgl** 2023-12-14 07:13 UTC

**Comment by Sumit-Mukherjee** [comment] 2023-12-14 12:07
Thanks for the clarification. I also figured out later after posting this comment that pyunicorn is incompatible with the python 3.9. I have created a separate environment with python 3.7.16 and installed pyunicorn there.

**Comment by ntfrgl** [comment] 2023-12-15 02:57
@Sumit-Mukherjee, it sounds like you have decided to keep using Pyunicorn `v0.6.1` from **2019** on top of **Python 3.7**, whose [full official support ended](https://en.wikipedia.org/wiki/History_of_Python#Table_of_versions) in **2020**. Of course, you are free to use as old a version as you wish.

Let me, however, strongly recommend to you once more the **current development version** on the `master` branch, which is compatible with **Python 3.8-3.12** and which has more features and tutorials, fewer bugs and better testing, as a result of all the work that happened in the period **2019-2023**.

In case you are unsure about what I meant by *"installing from the `master` branch"*, please have a look at the official `pip` documentation for how to install Python packages from [version control](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-from-vcs) or from a [local source tree](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-from-a-local-src-tree). In contrast, what you did was installing from the [Python Package Index](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-from-pypi), which is why you ended up with the *latest official release* `v0.6.1`.

**Comment by Sumit-Mukherjee** [comment] 2023-12-15 03:16
Thank you for the suggestion. I'll give pyunicorn's latest version a try in
my python 3.9 environment.

Cheers
Sumit
